
obj-y += net/
obj-y += serial/
obj-y += adc/
obj-y += nand/
obj-y += button/
obj-y += sunshine/
obj-y += dma/
obj-y += display/

#obj-y += button.o interrupt.o led.o mmu.o uart.o nand.o dma.o lcd.o bmp.o ts.o dm9000.o

